git-rebase-all: report if branches are now merged

diff --git a/git-rebase-all b/git-rebase-all
--- a/git-rebase-all
+++ b/git-rebase-all
@@ -9,13 +9,19 @@ BLACKLIST=$(git config --get rebase-all.blacklist) || true
 # Always blacklist master
 #BLACKLIST="$BLACKLIST master"
 
+COUNT=0
+SKIPPED=0
+FAILED=0
+
 bolden() {
     BOLD=`tput bold`
     NORMAL=`tput sgr0`
     echo "${BOLD}$*${NORMAL}"
 }
 report_ok() {
-    echo -e "$(tput setaf 2)SUCCESS:$(tput sgr0) $*"
+    HEADER=$1
+    shift
+    echo -e "$(tput setaf 2)$HEADER:$(tput sgr0) $*"
 }
 report_skip() {
     echo -e "$(tput setaf 3)SKIP:$(tput sgr0) $*"
@@ -42,41 +48,47 @@ get_upstream() {
     git rev-parse --abbrev-ref --symbolic-full-name $NAME@{upstream} 2>/dev/null
 }
 
+# 0 if $1 and $2 are the same SHA, 1 otherwise
+is_same() {
+    test $(git rev-parse $1) = $(git rev-parse $2)
+}
+
 # Rebase $1 to it's upstream branch
 try_rebase() {
     NAME=$1
     UPSTREAM=$(get_upstream $NAME)
     if test -z $UPSTREAM; then
         report_skip $NAME has no upstream set
+        SKIPPED=$((SKIPPED + 1))
         return 1
     fi
     git rebase --quiet $UPSTREAM $NAME 2>/dev/null
     if [ $? -eq 0 ] ; then
-        report_ok rebased $NAME to $UPSTREAM
+        if is_same $NAME $UPSTREAM; then
+            report_ok MERGED $NAME is now $UPSTREAM
+        else
+            report_ok SUCCESS rebased $NAME to $UPSTREAM
+        fi
         return 0
     else
         report_fail $NAME does not rebase to $UPSTREAM
         git rebase --abort
+        FAILED=$((FAILED + 1))
         return 1
     fi
 }
-
-COUNT=0
-FAILED=0
 
 BRANCHES=$(git for-each-ref refs/heads --format='%(refname:strip=2)')
 for NAME in $BRANCHES; do
     COUNT=$((COUNT + 1))
  
     check_blacklisted $NAME || continue
-    if ! try_rebase $NAME; then
-        FAILED=$((FAILED + 1))
-    fi
+    try_rebase $NAME || :
 done
 
 git checkout --quiet master
 
 echo
-echo "Rebased $COUNT branches, $FAILED didn't rebase successfully."
+echo "Rebased $COUNT branches, $SKIPPED skipped, $FAILED didn't rebase successfully."
 
 git branch --verbose
